<template>
  <div class="min-h-screen bg-[#0a0a0a] text-zinc-100">
    <div class="max-w- mx-auto p-6 md:p-8">
      <div class="flex justify-between mb-8"><div><div class="text- tracking-[0.3em] text-zinc-500 font-mono uppercase">System Pipeline</div><h1 class="text-4xl font-black">Extraction Engine</h1></div><div class="flex gap-3"><NuxtLink to="/home" class="h-10 px-5 rounded-full bg-zinc-900 border border-zinc-800 text-sm font-mono flex items-center">← HOME</NuxtLink><NuxtLink to="/staging" class="h-10 px-5 rounded-full bg-zinc-900 border border-zinc-800 text-sm font-mono flex items-center">STAGING →</NuxtLink></div></div>
      <div v-if="statusMsg" :class="['mb-6 rounded-xl border px-4 py-3 font-mono text-sm', isError?'bg-red-950/40 border-red-900 text-red-300':'bg-zinc-900 border-zinc-800']">{{ statusMsg }}</div>
      <div class="grid md:grid-cols-2 gap-6 mb-8"><div class="rounded- bg-zinc-900 border border-zinc-800 p-6"><h3 class="font-bold mb-4">YouTube Stream Ingest</h3><input v-model="targetPlaylistId" placeholder="Playlist ID" class="w-full bg-zinc-950 border border-zinc-800 rounded-xl px-4 py-3 text-sm"/><button @click="fetchYouTube" :disabled="isProcessing" class="w-full mt-4 bg-white text-black font-bold py-3 rounded-xl disabled:opacity-30">{{ isProcessing?'PROCESSING...':'FETCH TO PREVIEW' }}</button></div><div class="rounded- bg-zinc-900 border border-zinc-800 p-6"><h3 class="font-bold mb-4">Local Sync Ingest</h3><div class="flex bg-zinc-950 p-1 rounded-full border border-zinc-800 w-fit mb-4"><button @click="uploadMode='folder'" :class="['px-4 py-1.5 rounded-full text-xs font-bold', uploadMode==='folder'?'bg-white text-black':'text-zinc-500']">Folder</button><button @click="uploadMode='file'" :class="['px-4 py-1.5 rounded-full text-xs font-bold', uploadMode==='file'?'bg-white text-black':'text-zinc-500']">Files</button></div><input v-if="uploadMode==='folder'" type="file" webkitdirectory directory multiple @change="handleLocal" class="block w-full text-sm file:mr-4 file:py-2 file:px-4 file:rounded-full file:bg-zinc-800 file:text-white bg-zinc-950 border border-zinc-800 rounded-xl p-1"/><input v-else type="file" multiple accept=".mp3,.wav,.m4a,.flac,.ogg,.aac" @change="handleLocal" class="block w-full text-sm file:mr-4 file:py-2 file:px-4 file:rounded-full file:bg-zinc-800 file:text-white bg-zinc-950 border border-zinc-800 rounded-xl p-1"/></div></div>
      <div v-if="extractedList.length>0" class="rounded- bg-zinc-900 border border-zinc-800 overflow-hidden"><div class="flex justify-between px-6 py-4 border-b border-zinc-800"><span class="font-mono text-xs">PREVIEW ({{ extractedList.length }})</span><div class="flex gap-2"><span class="text- bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 px-3 py-1 rounded-full">{{ extractedList.length }} READY</span><button @click="extractedList=[]" class="text- border border-zinc-700 px-3 py-1 rounded-full">CLEAR</button></div></div><table class="w-full text-sm text-left"><thead class="bg-zinc-950 text- font-mono text-zinc-500"><tr><th class="px-6 py-3"><input type="checkbox" :checked="isAllSelected" @change="toggleAll" class="accent-white"/></th><th class="px-4 py-3">File</th><th class="px-4 py-3">Artist</th><th class="px-4 py-3">Title</th></tr></thead><tbody class="divide-y divide-zinc-800"><tr v-for="(item,i) in extractedList" :key="i"><td class="px-6 py-3"><input type="checkbox" v-model="item.IsSelected" class="accent-white"/></td><td class="px-4 py-3 font-mono text-xs text-zinc-400">{{ item.FileName }}</td><td class="px-4 py-3">{{ item.Artist||'—' }}</td><td class="px-4 py-3">{{ item.Title }}</td></tr></tbody></table><div class="p-4 bg-zinc-950 flex justify-end"><button @click="commit" :disabled="isProcessing" class="bg-white text-black font-black text-sm px-8 py-3 rounded-full disabled:opacity-30">COMMIT {{ extractedList.filter(i=>i.IsSelected).length }} TO STAGING</button></div></div>
    </div>
  </div>
</template>
<script setup lang="ts">
const statusMsg=ref(''); const isError=ref(false); const isProcessing=ref(false); const uploadMode=ref<'folder'|'file'>('folder'); const targetPlaylistId=ref('URL'); const extractedList=ref<any[]>([]);
const isAllSelected=computed(()=> extractedList.value.length>0 && extractedList.value.every((i:any)=>i.IsSelected));
const parseFromFilename=(name:string)=>{ const clean=name.replace(/\.[^/.]+$/,''); const p=clean.split(' - '); if(p.length>=2) return {artist:p[0].trim(),title:p.slice(1).join(' - ').trim()}; return {artist:'',title:clean} };
const fetchYouTube=async()=>{ isProcessing.value=true; const data=await $fetch('/api/youtube/playlist',{method:'POST',body:{playlistId:targetPlaylistId.value}}); extractedList.value.push(...(data as any[]).map((d:any)=>({FileName:d.videoId,Title:d.title,Artist:d.channelTitle,IsSelected:true}))); isProcessing.value=false; statusMsg.value=`${(data as any[]).length} lagu dari YouTube`; };
const handleLocal=async(e:Event)=>{ const input=e.target as HTMLInputElement; const files=Array.from(input.files||[]).slice(0,5000); const items=files.map(f=>{ const {artist,title}=parseFromFilename(f.name); return {FileName:f.name,Title:title,Artist:artist,IsSelected:true}}); extractedList.value.push(...items); input.value=''; };
const toggleAll=(e:Event)=>{ const c=(e.target as HTMLInputElement).checked; extractedList.value.forEach((i:any)=>i.IsSelected=c) };
const commit=async()=>{ const sel=extractedList.value.filter((i:any)=>i.IsSelected); if(!sel.length) return; isProcessing.value=true; await $fetch('/api/raw-songs/bulk',{method:'POST',body:sel.map((i:any)=>({FileName:i.FileName,Title:i.Title,Artist:i.Artist,YoutubeVideoId:i.FileName}))}); extractedList.value=extractedList.value.filter((i:any)=>!i.IsSelected); statusMsg.value=`${sel.length} masuk staging`; isProcessing.value=false; };
</script>
